language: ruby

rvm:
  - 2.5
  - 2.6

cache:
  directories:
  - $HOME/gnatsd

before_install:
  - bash ./scripts/install_gnatsd.sh

before_script:
  - export PATH=$HOME/gnatsd:$PATH

sudo: required
dist: xenial
bundler_args: --without server
